### ISSUE TITLE
用一键脚本启动不了，提示BaiduPCSWeb 启动失败

### ISSUE THREAD

**Issue by Mydong** [user1121114685/baidupcsweb#1]
在vultr上用一键脚本安装了，但是无法启动，端口也尝试修改了：
![image](https://user-images.githubusercontent.com/14023137/49990258-f471d900-ffb7-11e8-805c-2d56210dba98.png)
![image](https://user-images.githubusercontent.com/14023137/49990292-153a2e80-ffb8-11e8-9df7-758e2ea61c62.png)

**Comment by user1121114685** [comment]
## 这是端口错误，你尝试下这个 命令直接启动 .
`nohup /usr/local/BaiduPCSWeb/BaiduPCS-Go web --port 5299 2>&1 &`

另外你可以使用bash -vx BDW.sh 设置端口。截图给我吗？

**Comment by user1121114685** [comment]
## 你应该是个例。
我在搬瓦工上ubuntu测试过，在自己家里的debian 也测试过，就是没测试centos！

这完全属于Prot文件设置或者下载失败，

**Comment by user1121114685** [comment]
## 我想我找到了问题所在，并修复了他，请重新安装试试

**Comment by Mydong** [comment]
@user1121114685 感谢作者，按照上面的这个不住也解决了，没有重新安装。现在已经启动。
![image](https://user-images.githubusercontent.com/14023137/49991374-d3ab8280-ffbb-11e8-8b3c-339c62e8138e.png)
##### 按照下面这两行设置的。
![image](https://user-images.githubusercontent.com/14023137/49991385-d9a16380-ffbb-11e8-800f-57c0b6cf5c4c.png)

我现在重新卸载安装一下，测试，反馈

**Comment by Mydong** [comment]
重新安装也可以了。谢谢，谢谢作者哈。 # #

**Comment by user1121114685** [comment]
客气了，是我考虑不周。导致参数并没有传递过去。
