### ISSUE TITLE
可以更简洁些

### ISSUE THREAD

**Issue by rachpt** [user1121114685/baidupcsweb#2]
26行： [[ $EUID != 0 ]] && echo 比较数字准确应该使用 -ne ，要当成字符串，最好显示 ‘0’；
echo -e 的 -e 其实有点多余，-e 主要是为了使用 “\c \n”这些的；
32行： grep -q -E -i "debian" 可以合并 grep -qEi "debian"；
51行： 最好使用 $()  而不是 ``，前者兼容性更好，并且支持嵌套；
84行： if [[ -z ${BaiduPCS_Web_new_ver} ]]; then 直接使用 if [[ $BaiduPCS_Web_new_ver ]]; then 就行，对于可能出现空格的变量应使用双引号(双中括号不必要)；
87行： [[ -z "${BaiduPCS_Web_new_ver}" ]] && echo "取消..." && exit 1 
这样会更好 [[ $BaiduPCS_Web_new_ver ]] || （ echo "取消..." ; exit 1 )

如果系统未安装 wget(这个不是所有发行版默认有的) 会运行不了。

227行，一次可以 rm 多个文件的，rm -rf "${BaiduPCS_Go}" "${Folder}" "${file}" "${Folder}/port"；

最后 对于一行很长的代码建议使用将 tab 转成2个或者4个空格，必要的时候可以使用 \ 续行，unix哲学一行不超过 80字符。

**Comment by user1121114685** [comment]
## 感谢大佬指点！
大佬细心指点使我学习了更多。我没有系统的学过shell语言。感谢大佬了！

**Comment by user1121114685** [comment]
大佬，我已经更正一部分了！但是还是有很多-e 没有修改！我想再观察看看！
