### ISSUE TITLE
Connection timed out.

### ISSUE THREAD

**Issue by ntgeralt** [user1121114685/baidupcsweb#3]
please check.
Connecting to qiniu.zoranjojo.top (qiniu.zoranjojo.top)|59.108.155.217|:80... failed: Connection timed out.
Connecting to qiniu.zoranjojo.top (qiniu.zoranjojo.top)|59.108.155.228|:80... failed: Connection timed out.
Connecting to qiniu.zoranjojo.top (qiniu.zoranjojo.top)|59.108.155.229|:80... failed: Connection timed out.
Connecting to qiniu.zoranjojo.top (qiniu.zoranjojo.top)|59.108.155.216|:80... failed: Connection timed out.
Connecting to qiniu.zoranjojo.top (qiniu.zoranjojo.top)|59.108.155.218|:80... failed: Connection timed out.
Connecting to qiniu.zoranjojo.top (qiniu.zoranjojo.top)|59.108.155.215|:80... failed: Connection timed out.
Retrying.

**Comment by user1121114685** [comment]
do you try again?

---
你有再尝试一下吗？

---

**Comment by ntgeralt** [comment]
> do you try again?
> 
> 你有再尝试一下吗？

发现是谷歌云给了个tcp阻断的vps我，换个ip正常了。
