### ISSUE TITLE
怎么也不随便把路由器的也弄了

### ISSUE THREAD

**Issue by tangzhi1996** [user1121114685/baidupcsweb#4]
如题，免配置，直接运行脚本了，wget到路由器的tmp里面，然后运行了，或者通过选择的方式自己选择处理器的平台，通过 cat /proc/cpuinfo自己确定，baidupsc-web版本的平台还是很多的

**Comment by user1121114685** [comment]
其实不是想象那么简单，每个平台有每个平台的局限。不是单一的拷贝，下载就可以的。一般路由器都有人单独提供插件或者其他的方式的。

**Comment by tangzhi1996** [comment]
有个屁，没有，没有
 
---原始邮件---
发件人: "联盟少侠"<notifications@github.com>
发送时间: 2019年6月25日 08:38:11
收件人: "user1121114685/baidupcsweb"<baidupcsweb@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"tangzhi1996"<1010239577@qq.com>;
主题: Re: [user1121114685/baidupcsweb] 怎么也不随便把路由器的也弄了 (#4)



其实不是想象那么简单，每个平台有每个平台的局限。不是单一的拷贝，下载就可以的。一般路由器都有人单独提供插件或者其他的方式的。

**Comment by user1121114685** [comment]
真没办法每个系统都适配。只有自己修改下脚本。
