### ISSUE TITLE
大佬，web那边更新3.7.0了，你该更新脚本了

### ISSUE THREAD

**Issue by lior1995** [user1121114685/baidupcsweb#8]
rt，大佬，web那边更新3.7.0了，你该更新脚本了，现在用这个脚本，最新的3.7.0无法安装

**Comment by user1121114685** [comment]
收到。

--------------原始邮件--------------
发件人："smartychen "<notifications@github.com&gt;;
发送时间：2020年4月17日(星期五) 下午4:46
收件人："user1121114685/baidupcsweb" <baidupcsweb@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[user1121114685/baidupcsweb] 大佬，web那边更新3.7.0了，你该更新脚本了 (#8)
-----------------------------------

 

 
rt，大佬，web那边更新3.7.0了，你该更新脚本了，现在用这个脚本，最新的3.7.0无法安装

**Comment by user1121114685** [comment]
我试过了，我很早就更新到3.7了可以使用

**Comment by lior1995** [comment]
> 我试过了，我很早就更新到3.7了可以使用

[错误] BaiduPCS-Web服务 prot下载失败 !

大佬请问这个是什么问题，一直报这个错...

**Comment by user1121114685** [comment]
项目中的port下载失败了。可能是网络问题

**Comment by lior1995** [comment]
好的，我再去试一试，麻烦你了
